openapi: "3.0.0"

info:
  title: "Ash API"
  version: "0.0.1"

servers:
  - url: "/api/v0"

paths:
  "/info":
    get:
      tags:
        - "info"
      summary: "Get some information about this API."
      responses:
        "200":
          description: "Successful response with information."
  "/words/{token}":
    get:
      responses:
        "200":
          description: "Returns top 25 most similar words to {token}"
        "404":
          description: "{token} is not in the vocabulary"
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string